Repository nextcloud/twofactor_u2f, pull requests merged in 2018-10, with the labels that each got.

#247 Fix authentication/login registration id missing property
  lib/Service/U2FManager.php
Labels: 3. to review, bug

#248 Require Nextcloud 15+
  .travis.yml
  appinfo/info.xml
Labels: 3. to review

#249 Adapt to server changes
  composer.json
  composer.lock
  css/style.css
  js/settingsview.js
  lib/Provider/U2FProvider.php
  lib/Settings/Personal.php
  templates/challenge.php
  templates/personal.php
  tests/Unit/Provider/U2FProviderTest.php
Labels: 3. to review

#253 Fix/activity test
  .travis.yml
  composer.json
  tests/Unit/Activity/ProviderTest.php
Labels: 3. to review, bug

#257 Fix js coverage report
  .babelrc
  .gitignore
  .travis.yml
  package-lock.json
  package.json
  src/webpack.test.js
Labels: 3. to review, technical debt

#254 Move over to DB Migrations
  appinfo/database.xml
  lib/Migration/Version010601Date20181022142736.php
Labels: 3. to review, technical debt

#259 Add lint as composer script
  .travis.yml
  composer.json
Labels: 3. to review, technical debt
