Repository nextcloud/twofactor_u2f, pull requests merged in 2018-11, with the labels that each got.

#269 Release v2.0.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#285 Release v2.0.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#286 Fix missing Vue challenge page
  lib/Service/U2FManager.php
  src/components/Challenge.vue
  src/main-challenge.js
  src/webpack.common.js
  templates/challenge.php
Labels: 3. to review, bug, enhancement

#287 Release v2.0.2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#289 Release v2.0.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#292 Add Nextcloud 16 support and adjust build matrix accordingly
  .travis.yml
  appinfo/info.xml
  composer.json
  composer.lock
Labels: 3. to review, technical debt

#276 Support PHP 7.3
  .travis.yml
  appinfo/info.xml
Labels: 3. to review, enhancement
