Repository nextcloud/twofactor_u2f, pull requests merged in 2019-01, with the labels that each got.

#331 Fix build matrix for php7.0
  .travis.yml
  appinfo/info.xml
Labels: 3. to review, priority, technical debt

#326 Bump christophwurst/nextcloud
  composer.json
Labels: 3. to review, technical debt

#340 Use QBMapper
  lib/Db/RegistrationMapper.php
Labels: 3. to review, technical debt

#344 Log the error metadata as well
  src/components/Challenge.vue
  src/main-challenge.js
Labels: 3. to review, enhancement, technical debt
