Repository nextcloud/twofactor_u2f, pull requests merged in 2019-10, with the labels that each got.

#550 Switch to official @nextcloud packages
  package-lock.json
  package.json
  src/components/AddDeviceDialog.vue
  src/components/Device.vue
  src/logger.js
  src/services/RegistrationService.js
Labels: 3. to review, technical debt

#543 Move to IEventDispatcher
  lib/Service/U2FManager.php
  tests/Unit/Service/U2FManagerTest.php
Labels: 3. to review, bug

#553 No need to bundle the store in the challenage js
  package-lock.json
  src/main-challenge.js
Labels: 3. to review, enhancement

#552 Do not import all of the vue-components
  src/components/Device.vue
Labels: 3. to review, enhancement
