Repository nextcloud/twofactor_u2f, pull requests merged in 2019-04, with the labels that each got.

#406 Add .jshintrc config file for scrutinizer
  .jshintrc
Labels: 4. to release, bug, technical debt

#412 Make provider display name translatable
  lib/Provider/U2FProvider.php
  tests/Unit/Provider/U2FProviderTest.php
Labels: 3. to review, bug

#413 Make warning stand out from text
  css/style.css
Labels: 4. to release, enhancement

#414 Release v2.1.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#419 Make app compatible with 17, drop 15
  .travis.yml
  appinfo/info.xml
  composer.json
  composer.lock
Labels: 3. to review, enhancement
