Repository nextcloud/twofactor_u2f, pull requests merged in 2020-01, with the labels that each got.

#616 Update README to reflect current Firefox status
  README.md
Labels: 3. to review

#629 Warn about appId mismatch
  src/components/AddDeviceDialog.vue
Labels: 3. to review, bug

#640 Switch to @nextcloud/vue
  package-lock.json
  package.json
  src/components/Device.vue
Labels: 3. to review, technical debt

#652 Add Nextcloud 19 support
  .travis.yml
  appinfo/info.xml
Labels: 3. to review
