Repository nextcloud/twofactor_u2f, pull requests merged in 2020-02, with the labels that each got.

#658 Revert "Bump christophwurst/nextcloud from 17.0.2 to 18.0.0"
  composer.json
  composer.lock
Labels: 3. to review, technical debt

#659 Add SoloKey
  README.md
Labels: 4. to release

#601 Use php7.4 instead of the snapshot
  .travis.yml
Labels: 2. developing, blocked, technical debt
